---
title: "Comparing_Effect_Sizes_Two_Linear_Models"
author: "Lauren Blake"
date: "November 4, 2017"
output: html_document
---

This is sample code using FSR instead of FDR cutoffs and makes log2 effect sizes comparisons.

```{r chunk-options, include=FALSE}
source("chunk-options.R")
```

```{r}
# Load libraries/data

library("edgeR")
library("limma")
library("plyr")
library("ggplot2")
library("ashr")

cpm.voom.cyclic <- readRDS("../data/human_chimp_orth_cpm_voom_cyclic.rds")
exp_methyl <- read.table("../data/human_chimp_orth_exp_methyl_7725_hum.txt", header = T, stringsAsFactors = F)
samples <- read.table("../data/human_chimp_orth_new_sample_info.txt", header = T,  stringsAsFactors = F)

# Get sample info
species <- as.data.frame(samples[,4])
tissue <- as.data.frame(samples[,5])
RIN <- as.data.frame(samples[,6])
```

## Run the ASH functions

```{r}
integration_ash <- function(chimp_human_heart, FSR_level){
FDR_level <- FSR_level
#tissue <- as.data.frame(samples[,5])
tissue <- as.data.frame(samples[,4])
tissue <- tissue[chimp_human_heart,]
tissue_no_extra <- droplevels.factor(tissue)


design <- model.matrix(~ as.factor(tissue_no_extra) + RIN[chimp_human_heart,])
fit_all <- lmFit(cpm.voom.cyclic[,chimp_human_heart], design)
fit_all <- eBayes(fit_all)


# Run ASH

# Prepare the data for ASH
tests <- colnames(fit_all$coefficients)
results <- vector(length = length(tests), mode = "list")
names(results) <- tests

# Perform multiple testing correction with adaptive shrinkage (ASH) 
 #
 # x - object MArrayLM from eBayes output
 # coef - coefficient tested by eBayes

run_ash <- function(x, coef){
  #stopifnot(class(x) == "MArrayLM", coef %in% colnames(x$coefficients),
  #             length(unique(x$df.total) == 1))
  result <- ash(betahat = x$coefficients[, coef], sebetahat = x$stdev.unscaled[, coef] * sqrt(x$s2.post), df = x$df.total[1])
  return(result)
}

get_results <- function(x, number = nrow(x$coefficients), sort.by = "none",
                        ...) {
  # x - object MArrayLM from eBayes output
  # ... - additional arguments passed to topTable
  stopifnot(class(x) == "MArrayLM")
  results <- topTable(x, number = number, sort.by = sort.by, ...)
  return(results)
}

# Get lfsr, lfdr, s value, q value, and a beta_est value. 
  # Extract limma results
  results <- get_results(fit_all, coef = tests[2])
  # Add mutliple testing correction with ASH
  output_ash <- run_ash(fit_all, coef = tests[2])
  results <- cbind(results, sebetahat = output_ash$data$s, lfsr = output_ash$result$lfsr,
                           lfdr = output_ash$result$lfdr, qvalue = output_ash$result$qvalue,
                           svalue = output_ash$result$svalue, beta_est = output_ash$result$PosteriorMean, se_est =
                             output_ash$result$PosteriorSD)

# Find the genes < FSR
#HvC_Heart_fit_all = topTable(fit_all, coef=2, adjust="BH", number=Inf, sort.by="none")
#HvC_Heart_fit_all_5perc <- HvC_Heart_fit_all[which(HvC_Heart_fit_all$adj.P.Val < FSR_level), ]
#HvC_Heart_fit_all_5perc <- results[which(results$qvalue < FSR_level), ]
HvC_Heart_fit_all_5perc <- results[which(results$svalue < FSR_level), ]


human_chimp_heart <-  rownames(exp_methyl) %in% HvC_Heart_fit_all_5perc$genes
human_chimp_heart <- as.data.frame(human_chimp_heart)
counts_genes_in <- cbind(exp_methyl, human_chimp_heart)
counts_genes_in_cutoff <- subset(counts_genes_in, human_chimp_heart == "TRUE")
counts_genes_in_cutoff <- counts_genes_in_cutoff[,1:79]  
expression_values_only <- counts_genes_in_cutoff[,2:32]
methylation_values_only <- counts_genes_in_cutoff[,49:79]
dim(expression_values_only)

## Obtain corrected data (regression for scenario 2) by regressing out RIN on a gene-by-gene basis
resid_methyl <- array(0, dim = c(nrow(expression_values_only), length(chimp_human_heart))) 
expression_values <- as.data.frame(expression_values_only)
methylation_values <- as.data.frame(methylation_values_only)
for (i in 1:nrow(expression_values_only)){
  resid_methyl[i,] <- lm(t(expression_values_only[i,chimp_human_heart]) ~ t(methylation_values_only[i,chimp_human_heart]))$resid
}
rownames(resid_methyl) <- rownames(expression_values_only)

# Scenario 1

fit1 <- lmFit(expression_values_only[, chimp_human_heart], design)
fit1 <- eBayes(fit1)

  results <- get_results(fit1, coef = tests[2])
  # Add mutliple testing correction with ASH
  output_ash <- run_ash(fit1, coef = tests[2])
  results_fit1 <- cbind(results, sebetahat = output_ash$data$s, lfsr = output_ash$result$lfsr,
                           lfdr = output_ash$result$lfdr, qvalue = output_ash$result$qvalue,
                           svalue = output_ash$result$svalue, beta_est = output_ash$result$PosteriorMean, se_est =
                             output_ash$result$PosteriorSD)


# Scenario 2

fit2 <- lmFit(resid_methyl, design)
fit2 <- eBayes(fit2)

results <- get_results(fit2, coef = tests[2])
  # Add mutliple testing correction with ASH
output_ash <- run_ash(fit2, coef = tests[2])
results_fit2 <- cbind(results, sebetahat = output_ash$data$s, lfsr = output_ash$result$lfsr,
                           lfdr = output_ash$result$lfdr, qvalue = output_ash$result$qvalue,
                           svalue = output_ash$result$svalue, beta_est = output_ash$result$PosteriorMean, se_est =
                             output_ash$result$PosteriorSD)

# Bind beta values from fit1 and DE from fit2 together

HvC_Heart_fits12 <- as.data.frame(cbind(rownames(results_fit1), results_fit1$beta_est, results_fit2$beta_est), stringsAsFactors = FALSE)
HvC_Heart_fits12[,2] <- as.numeric(HvC_Heart_fits12[,2])
HvC_Heart_fits12[,3] <- as.numeric(HvC_Heart_fits12[,3])
colnames(HvC_Heart_fits12) <- c("genes", "beta1_est", "beta2_est")

# Count the number of genes that have bet
DE_both <- HvC_Heart_fits12[which(HvC_Heart_fits12$fit1_FDR < FDR_level &  HvC_Heart_fits12$fit2_FDR < FDR_level),]
nrow(DE_both)

DE_before <- HvC_Heart_fits12[which(HvC_Heart_fits12$fit1_FDR < FDR_level &  HvC_Heart_fits12$fit2_FDR > FDR_level),]
nrow(DE_before)

DE_after <- HvC_Heart_fits12[which(HvC_Heart_fits12$fit1_FDR > FDR_level &  HvC_Heart_fits12$fit2_FDR < FDR_level),]
nrow(DE_after)

important_returns <- rbind(HvC_Heart_fits12)
return(important_returns)
}

human_heart_kidney <- integration_ash(c(17, 20, 21, 24, 25, 28, 29), 0.05)

plot(human_heart_kidney[,2], human_heart_kidney[,3], xlim = c(-10,10), ylim = c(-10,10), xlab = c("Effect size from lm 1"), ylab = c("Effect size from lm 2 (corrected gene exp. data)"))
t.test(human_heart_kidney[,2], human_heart_kidney[,3])


as.numeric(summary((log2(abs(human_heart_kidney[,2]/human_heart_kidney[,3])) > 5) == TRUE)[3])
summary((log2(abs(human_heart_kidney[,2]/human_heart_kidney[,3])) > 3) == TRUE)
summary((log2(abs(human_heart_kidney[,2]/human_heart_kidney[,3])) > 2) == TRUE)


HC_heart <- integration_ash(c(2, 6, 10, 14, 17, 21, 25, 29), 0.05)
HC_heart_k <- cbind(HC_heart, log2(abs(HC_heart[,2]/HC_heart[,3]))  > 2)
colnames(HC_heart_k) <- c("genes", "beta1_est", "beta2_est", "logFC")
HC_heart_k$logFC[HC_heart_k$logFC == TRUE] <- "red"
HC_heart_k$logFC[HC_heart_k$logFC == FALSE] <- "black"
plot(HC_heart[,2], HC_heart[,3], xlim = c(-10,10), ylim = c(-10,10), xlab = c("Effect size from lm 1"), col = HC_heart_k$logFC, ylab = c("Effect size from lm 2 (corrected gene exp. data)"), main = "Effect size of species (in DS genes, FSR 1%)")

summary((log2(abs(HC_heart[,2]/HC_heart[,3])) > 2) == TRUE)
42/770

HC_heart_actual <- integration_ash(c(1, 5, 9, 13, 20, 24, 28), 0.05)
plot(HC_heart_actual[,2], HC_heart_actual[,3], xlim = c(-10,10), ylim = c(-10,10), xlab = c("Effect size from lm 1"), ylab = c("Effect size from lm 2 (corrected gene exp. data)"))
summary((log2(abs(HC_heart_actual[,2]/HC_heart_actual[,3])) > 2) == TRUE)
206/(2161+206)
```

## Comparison with permutations

```{r}
integration_ash_perm <- function(chimp_human_heart, FSR_level){
FDR_level <- FSR_level
tissue <- as.data.frame(samples[,5])
tissue <- tissue[chimp_human_heart,]
tissue_no_extra <- droplevels.factor(tissue)


design <- model.matrix(~ as.factor(tissue_no_extra) + RIN[chimp_human_heart,])
fit_all <- lmFit(cpm.voom.cyclic[,chimp_human_heart], design)
fit_all <- eBayes(fit_all)


# Run ASH

# Prepare the data for ASH
tests <- colnames(fit_all$coefficients)
results <- vector(length = length(tests), mode = "list")
names(results) <- tests

# Perform multiple testing correction with adaptive shrinkage (ASH) 
 #
 # x - object MArrayLM from eBayes output
 # coef - coefficient tested by eBayes

run_ash <- function(x, coef){
  #stopifnot(class(x) == "MArrayLM", coef %in% colnames(x$coefficients),
  #             length(unique(x$df.total) == 1))
  result <- ash(betahat = x$coefficients[, coef], sebetahat = x$stdev.unscaled[, coef] * sqrt(x$s2.post), df = x$df.total[1])
  return(result)
}

get_results <- function(x, number = nrow(x$coefficients), sort.by = "none",
                        ...) {
  # x - object MArrayLM from eBayes output
  # ... - additional arguments passed to topTable
  stopifnot(class(x) == "MArrayLM")
  results <- topTable(x, number = number, sort.by = sort.by, ...)
  return(results)
}

# Get lfsr, lfdr, s value, q value, and a beta_est value. 
  # Extract limma results
  results <- get_results(fit_all, coef = tests[2])
  # Add mutliple testing correction with ASH
  output_ash <- run_ash(fit_all, coef = tests[2])
  results <- cbind(results, sebetahat = output_ash$data$s, lfsr = output_ash$result$lfsr,
                           lfdr = output_ash$result$lfdr, qvalue = output_ash$result$qvalue,
                           svalue = output_ash$result$svalue, beta_est = output_ash$result$PosteriorMean, se_est =
                             output_ash$result$PosteriorSD)

# Find the genes < FSR
#HvC_Heart_fit_all = topTable(fit_all, coef=2, adjust="BH", number=Inf, sort.by="none")
#HvC_Heart_fit_all_5perc <- HvC_Heart_fit_all[which(HvC_Heart_fit_all$adj.P.Val < FSR_level), ]
#HvC_Heart_fit_all_5perc <- results[which(results$qvalue < FSR_level), ]
HvC_Heart_fit_all_5perc <- results[which(results$svalue < FSR_level), ]


human_chimp_heart <-  rownames(exp_methyl) %in% HvC_Heart_fit_all_5perc$genes
human_chimp_heart <- as.data.frame(human_chimp_heart)
counts_genes_in <- cbind(exp_methyl, human_chimp_heart)
counts_genes_in_cutoff <- subset(counts_genes_in, human_chimp_heart == "TRUE")
counts_genes_in_cutoff <- counts_genes_in_cutoff[,1:79]  
expression_values_only <- counts_genes_in_cutoff[,2:32]
methylation_values_only <- counts_genes_in_cutoff[,49:79]
dim(expression_values_only)

## Obtain corrected data (regression for scenario 2) by regressing out RIN on a gene-by-gene basis
resid_methyl <- array(0, dim = c(nrow(expression_values_only), length(chimp_human_heart))) 
expression_values <- as.data.frame(expression_values_only)
methylation_values <- as.data.frame(methylation_values_only)
for (i in 1:nrow(expression_values_only)){
  resid_methyl[i,] <- lm(t(expression_values_only[i,chimp_human_heart]) ~ t(methylation_values_only[i,chimp_human_heart]))$resid
}
rownames(resid_methyl) <- rownames(expression_values_only)

# Scenario 1

fit1 <- lmFit(expression_values_only[, chimp_human_heart], design)
fit1 <- eBayes(fit1)

  results <- get_results(fit1, coef = tests[2])
  # Add mutliple testing correction with ASH
  output_ash <- run_ash(fit1, coef = tests[2])
  results_fit1 <- cbind(results, sebetahat = output_ash$data$s, lfsr = output_ash$result$lfsr,
                           lfdr = output_ash$result$lfdr, qvalue = output_ash$result$qvalue,
                           svalue = output_ash$result$svalue, beta_est = output_ash$result$PosteriorMean, se_est =
                             output_ash$result$PosteriorSD)


# Scenario 2

fit2 <- lmFit(resid_methyl, design)
fit2 <- eBayes(fit2)

results <- get_results(fit2, coef = tests[2])
  # Add mutliple testing correction with ASH
output_ash <- run_ash(fit2, coef = tests[2])
results_fit2 <- cbind(results, sebetahat = output_ash$data$s, lfsr = output_ash$result$lfsr,
                           lfdr = output_ash$result$lfdr, qvalue = output_ash$result$qvalue,
                           svalue = output_ash$result$svalue, beta_est = output_ash$result$PosteriorMean, se_est =
                             output_ash$result$PosteriorSD)

# Bind beta values from fit1 and DE from fit2 together

HvC_Heart_fits12 <- as.data.frame(cbind(rownames(results_fit1), results_fit1$beta_est, results_fit2$beta_est), stringsAsFactors = FALSE)
HvC_Heart_fits12[,2] <- as.numeric(HvC_Heart_fits12[,2])
HvC_Heart_fits12[,3] <- as.numeric(HvC_Heart_fits12[,3])
colnames(HvC_Heart_fits12) <- c("genes", "beta1_est", "beta2_est")

beta_twofold <- as.numeric(summary((log2(abs(human_heart_kidney[,2]/human_heart_kidney[,3])) > 2) == TRUE)[3])
beta_threefold <- as.numeric(summary((log2(abs(human_heart_kidney[,2]/human_heart_kidney[,3])) > 3) == TRUE)[3])
beta_fivefold <- as.numeric(summary((log2(abs(human_heart_kidney[,2]/human_heart_kidney[,3])) > 5) == TRUE)[3])


  ### Permute the methylation values, then re-run
  
run1000 <- array(0, dim = c(3, 1000)) 
  
  #for (k in 1:1000){
    for (k in 1:2){
    # Run 1 for all genes
    run1 <- array(0, dim = c(nrow(expression_values_only), length(chimp_human_heart))) 
    
    for (i in 1:nrow(expression_values_only)){
      df <- as.data.frame(methylation_values_only[i,chimp_human_heart])
      new_df <- as.data.frame(sample(df))
      run1[i,] <- t(new_df)
    }
    
    
    
    # Make an array to hold the residuals
    
    resid_methyl_perm <- array(0, dim = c(nrow(expression_values_only), length(chimp_human_heart))) 
    
    
    #for (i in 1:2){
    for (i in 1:nrow(expression_values_only)){
      resid_methyl_perm[i,] <- lm(t(expression_values_only[i,chimp_human_heart]) ~ run1[i,])$resid
    }
    
    rownames(resid_methyl_perm) <- rownames(expression_values_only)
    
    
    # Scenario 2
    
    fit2 <- lmFit(resid_methyl_perm, design)
    fit2 <- eBayes(fit2)
    #HvC_Heart_perm = topTable(fit2, coef=2, adjust="BH", number=Inf, sort.by="none")
    
    results <- get_results(fit2, coef = tests[2])
    # Add mutliple testing correction with ASH
    output_ash <- run_ash(fit2, coef = tests[2])
    results_fit2 <- cbind(results, sebetahat = output_ash$data$s, lfsr = output_ash$result$lfsr,
                          lfdr = output_ash$result$lfdr, qvalue = output_ash$result$qvalue,
                          svalue = output_ash$result$svalue, beta_est = output_ash$result$PosteriorMean, se_est =
                            output_ash$result$PosteriorSD)
    
    HvCHeart_DE_perm <- cbind(human_heart_kidney[,2],  results_fit2$beta_est)

beta_perm_twofold <- as.numeric(summary((log2(abs(HvCHeart_DE_perm[,1]/HvCHeart_DE_perm[,2])) > 2) == TRUE)[3])
beta_perm_threefold <- as.numeric(summary((log2(abs(HvCHeart_DE_perm[,1]/HvCHeart_DE_perm[,2])) > 3) == TRUE)[3])
beta_perm_fivefold <- as.numeric(summary((log2(abs(HvCHeart_DE_perm[,1]/HvCHeart_DE_perm[,2])) > 5) == TRUE)[3])
 new_numbers <- rbind(beta_perm_twofold, beta_perm_threefold, beta_perm_fivefold)
 
  new_numbers <- rbind(beta_perm_twofold, beta_perm_threefold, beta_perm_fivefold)
  
  run1000[,k] <- new_numbers
  
    }

  row1 <- median(run1000[1,1:2])
  row2 <- median(run1000[2,1:2])
  row3 <- median(run1000[3,1:2])

# Combine everything together 
  HvCHeart_beta_perm <- rbind(beta_twofold, beta_threefold, beta_fivefold, row1, row2, row3)
  
    return(HvCHeart_beta_perm)
  
}
  

human_heart_kidney_perm <- integration_ash_perm(c(17, 20, 21, 24, 25, 28, 29), 0.05)

summary((log2(abs(human_heart_kidney_perm[,1]/human_heart_kidney_perm[,2])) > 5) == TRUE)
summary((log2(abs(human_heart_kidney_perm[,1]/human_heart_kidney_perm[,2])) > 3) == TRUE)
summary((log2(abs(human_heart_kidney_perm[,1]/human_heart_kidney_perm[,2])) > 2) == TRUE)

```

